spring.application.name=emp_mgt_backend
spring.datasource.url=jdbc:mysql://localhost:3306/trainingdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8040